<?php

namespace OutCaptcha;

/**
 * Test class for Dictionary.
 * Generated by PHPUnit on 2012-03-01 at 21:52:48.
 */
class DictionaryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @test 
     * @dataProvider getRandomProvider
     */
    public function getRandom($source, $expected)
    {
        $dic = new Dictionary($source);
        
        $result = $dic->getRandom();
        
        $this->assertEquals($expected, $result);
    }
    
    /**
     * @return array 
     */
    public function getRandomProvider()
    {
        $testCases = array();
        
        $testCases[] = array(
            __DIR__ . '/dic/multy_en.json', 
            array('Dog', array('dog', 'dogs'))
        );
        
        $testCases[] = array(
            __DIR__ . '/dic/en.json', 
            array('Dog', 'dog')
        );
        
        $testCases[] = array(
            array('Dog' => 'dog'), 
            array('Dog', 'dog')
        );
        
        $testCases[] = array(
            array('Dog' => array('dog', 'dogs')), 
            array('Dog',  array('dog', 'dogs'))
        );
        
        return $testCases;
    }
    
    /**
     * @test 
     */
    public function getAll()
    {
        $source = array('Dog' => 'dog');
        $dic = new Dictionary($source);
        
        $result = $dic->getAll();
        
        $this->assertEquals($source, $result);
    }
    
    /**
     * @test 
     */
    public function getAnswer()
    {
        $source = array('Dog' => 'dog', 'Cat' => 'cat');
        $dic = new Dictionary($source);
        
        $result = $dic->getAnswer('Cat');
        $this->assertEquals('cat', $result);
        
        
        $result = $dic->getAnswer(uniqid());
        $this->assertNull($result);
    }
    
    /**
     * @test 
     * @expectedException OutCaptcha\Exception
     */
    public function notValidSource()
    {
        $dic = new Dictionary(uniqid());
    }
}