<?php

namespace OutCaptcha;

/**
 * Test class for OutCaptcha.
 * Generated by PHPUnit on 2012-02-26 at 18:02:30.
 */
class OutCaptchaTest extends \PHPUnit_Framework_TestCase {

    /**
     * @test 
     */
    public function generate() {
       $options = new Options();
       $outCaptcha = new OutCaptcha($options);
       $imageBuilderMock = $this->getMock('OutCaptcha\ImageBuilder');
       $imageProviderMock = $this->getMock('OutCaptcha\ImagesProvider');
       
       
       $imageProviderMock
             ->expects($this->any())
             ->method('getImages')
             ->will($this->returnValue(array()));
       
       $expectedResult = uniqid();
       $imageBuilderMock
             ->expects($this->any())
             ->method('getResult')
             ->will($this->returnValue($expectedResult));
       
       $outCaptcha->setImageBuilder($imageBuilderMock);
       $outCaptcha->setImageProvider($imageProviderMock);
       
       
       $result = $outCaptcha->generate(uniqid());
        $this->assertEquals($expectedResult, $result);
       
       
    }

}
