<?php

namespace OutCaptcha\ImagesProvider;

use PHPUnit_Framework_Constraint_Count as SameSize;

/**
 * Test class for Google.
 * Generated by PHPUnit on 2012-02-26 at 19:23:06.
 */
class GoogleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @test
     * @covers OutCaptcha\ImagesProvider\Google::getImages
     */
    public function getImages()
    {
        $crawlerMock = $this->getMock('OutCaptcha\Crawler');
        $googleProvider = new Google($crawlerMock);

        $response = file_get_contents(__DIR__ . '/mockGoogleImages.html');

        $crawlerMock
                ->expects($this->any())
                ->method('request')
                ->will($this->returnValue($response));
        $expectedResult = array(1, 2, 3);
        $crawlerMock
                ->expects($this->any())
                ->method('downloadFiles')
                ->with(new SameSize(246))
                ->will($this->returnValue($expectedResult));

        $result = $googleProvider->getImages(uniqid(), 3);

        $this->assertCount(count($expectedResult), $result);
    }

}